version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
      - image: postgres:9.5
        environment:
          POSTGRES_DB: chess-quest_test
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run:
          name: which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: 
          name: DB setup
          command: bundle exec rails db:{create,migrate}
